services:
  xm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app

  postgres:
    image: 'postgres:15.8'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myverysecretpassword
      POSTGRES_DB: docker_home
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
      - ./sql/xmapi.sql:/docker-entrypoint-initdb.d/create_tables.sql